accumulate_grad_batches: 1
batch_size: 2048
bias: true
data_set: QM9
dropout: 0.1
learning_rate: 0.0001
lr_decay_epochs: 10000
lr_min_ratio: 0.1
lr_warmup_epochs: 50
max_epochs: 10000
n_embd: 768
n_embd_fm: 1536
n_head: 12
n_layer: 12
n_layers_fm: 6
noise_std: 1.4
rope: false
source_target_split: cyclic
time_step_resampling: 16
time_step_sampling: logit_normal
vocab_size: 6
weight_decay: 1.0e-06

