accumulate_grad_batches: 1
batch_size: 2048
bias: true
block_size: 512
data_set: QM9_small_vocab
data_split: edm_split
dropout: 0.1
fm_conditioning: ada
learning_rate: 0.0001
max_epochs: 5000
n_embd: 720
n_embd_fm: 1440
n_head: 12
n_layer: 12
n_layers_fm: 6
pooling: add
time_step_resampling: 4
time_step_sampling: logit_normal
vocab_size: 16
weight_decay: 1.0e-06
