block_size: 512
vocab_size: 16
n_layer: 12
n_head: 12
n_embd: 720
n_embd_fm: 1440
n_layers_fm: 6
dropout: 0.2
bias: True
data_set: QM9
batch_size: 2048
data_split: edm_split
accumulate_grad_batches: 1
max_epochs: 5000
weight_decay: 1.e-6
learning_rate: 1.e-4
pooling: add
fm_conditioning: ada
time_step_sampling: logit_normal
