block_size: 1024
vocab_size: 118
n_layer: 12
n_head: 12
n_embd: 720
dropout: 0.2
bias: True
data_set: QM9
batch_size: 512
data_split: edm_split
accumulate_grad_batches: 1
max_epochs: 1000
weight_decay: 1.e-6
learning_rate: 1.e-4
